### ISSUE TITLE
What does the optional patch do in detail?

### ISSUE THREAD

**Issue by Instandhaltung** [FUComplete/Patch#10]
Hey! Great patch so far! I wonder what the audio restoration patch do in detail? What was restored? Are the sounds of higher quality? Is the music different? Also, since you can inject files from dos to FU: I always thought that it would be great if the ps2 textures (especially monster textures) could be injected into the psp version to improve the graphics. I don't like texture mods or backports from later titles, but the higher resolution official MH2 textures would be great. Do you think this could be possible?

Looking forward to v 1.1 :)

**Comment by Darthagnon** [comment]
Hi-res textures for MHFU can be found on the [MH Classic HD Discord](https://discord.com/invite/zVdyVBx) and [here](https://github.com/grimmtusk/MHFU-HD). These hi-res textures can be used (separately) via [PPSSPP](https://ppsspp.org/). It is probably impossible to patch HD textures into the game ISO (but no reason to do so as PPSSPP is the only place they're usable and it already loads them).

**Comment by Instandhaltung** [comment]
> Hi-res textures for MHFU can be found on the [MH Classic HD Discord](https://discord.com/invite/zVdyVBx) and [here](https://github.com/grimmtusk/MHFU-HD). These hi-res textures can be used (separately) via [PPSSPP](https://ppsspp.org/). It is probably impossible to patch HD textures into the game ISO (but no reason to do so as PPSSPP is the only place they're usable and it already loads them).

Sure, thanks for the reply. I don't like those "self made" textures though. I respect the work the players put into them, but I also think that they are made with way too much "artistic liberty". They sometimes look very different from the original game. But yeah, thanks 🙂

**Comment by IncognitoMan** [comment]
> Hey! Great patch so far! I wonder what the audio restoration patch do in detail? What was restored? Are the sounds of higher quality? Is the music different? Also, since you can inject files from dos to FU: I always thought that it would be great if the ps2 textures (especially monster textures) could be injected into the psp version to improve the graphics. I don't like texture mods or backports from later titles, but the higher resolution official MH2 textures would be great. Do you think this could be possible?
> 
> Looking forward to v 1.1 :)

In terms of what the audio patch does it restores the battle themes from Dos back into the game... portable series and the localization sorta mixed up the audio. P2 -> F2 -> P2G -> FU changed the audio quite a bit and IIRC P2 actually had basically all the Dos themes in place... however for whatever reason the quality was really bad.

The restored ones are taken from the OST and converted/looped appropriately. These would include:
* [Jungle](https://youtu.be/wP1Tiq74gWs)
* [Desert](https://youtu.be/Hjf1QfiTBbY) 
* [Swamp](https://youtu.be/ZRQT-QYB0_I)
* [Snowy Mountain](https://youtu.be/7T0Vp7okMhE)
* [Volcano](https://youtu.be/vHSCNxTjX1c)
* [Tower theme](https://youtu.be/f5ZNBm9EuEc) 

There's 2 other changes which will probably be removed since they don't really fit and I added them on request but seems like people don't like it. Those 2 being the "noticed" and "quest complete" audio. I'll look into possibly expanding the audio changes but keeping it to a minimal unless I can improve the quality.

As for the second part of the question... injections are doable however you are limited to a 256 color palette which would then require a "reduced" color version of the Dos textures. Because of this it's better to use PPSSPPs native texture replacement to get around the 256 color limit.

**Comment by Instandhaltung** [comment]
> 

I'd also approve the MHFU quest complete theme. Thank you for the hard work, and for the long answer. 
I thought it might be easier to port the textures for a result similar to mhp3rd or something 😅. Well, afaik there aren't any mhdos textures available anywhere. So for now we'll have to stick with the original ones. Thanks again

**Comment by Darthagnon** [comment]
>Sure, thanks for the reply. I don't like those "self made" textures though. I respect the work the players put into them, but I also think that they are made with way too much "artistic liberty". They sometimes look very different from the original game.

I get that. It's the reason I don't use many HD texture packs. I do feel the PSP Monster Hunters scale much better than the 3DS releases, though. 3DS versions, I use "minimal" texture packs, covering just the HUD, item icons, button prompts; some scenery elements are still noticeably pixellated. PSP versions, I don't use any textures, and everything looks fine.

**Comment by KnivezOfficial** [comment]
when acomplising a dlc quest there are no "Clear" sign when checking it again in the respective star rank
