### ISSUE TITLE
Can't play with normal games

### ISSUE THREAD

**Issue by TTTV191** [FUComplete/Patch#14]
Can't play with normal game except for 1.0 version as  well.

**Comment by Abbanon** [comment]
The reason why is explained here: #13 

But to summarize:
FUC currently isn't compatible with vanilla FU/P2G, because Incog is waiting on the user named Zack (from Hunsterverse) to implement the bits of code needed to allow non-broken crossplay.
Once Zack gets around to implementing said code, crossplay will be possible.
