### ISSUE TITLE
Quest injection does not seem to work for me. [Solution in comments]

### ISSUE THREAD

**Issue by Instandhaltung** [FUComplete/Patch#35]
Hey! I tried the quest injection app, but the game (English patch, 1.1, on Adrenaline) gives me an Error (80110306). 
I also tried to save the game again (I hoped that it would need the edit for more quests), but it did not work as well. What could cause this?

**Comment by IncognitoMan** [comment]
Was sent a few reports about this yesterday and it seems there's some additional check that PPSSPP ignores but a Vita/PSP cross references... 

The solution so far is to inject the quests into your save, load your savedata on PPSSPP and save. After that you can copy your savedata to your PSP/Vita and it will work.

![image](https://user-images.githubusercontent.com/5410031/154814897-983e0d64-7db4-43c1-bced-c207dac4fc4d.png)


I missed this because when I was testing injection I first tested on PPSSPP then copied my save to my Vita and it worked without issue... sorry about this.

I can only guy that whats giving the problem is `PARAM.SFO` but will have to dig further.

**Comment by Instandhaltung** [comment]
Thank you very much, will try that later.
Also thanks for you work. I really appreciate it.

**Comment by Instandhaltung** [comment]
Thank you very much, will try that later 👍
Also thanks for you work. I really appreciate it
