### ISSUE TITLE
[Feature Request] iOS HD textures for PS3 PKG emulation and PPSSPP ala. MH Portable 3rd HD Ver.

### ISSUE THREAD

**Issue by Hydra-Spectre** [FUComplete/Patch#44]
The iOS version of Monster Hunter Portable 2nd G/Freedom Unite apparently has higher-resolution assets.
Replacing the game with these assets would not work on real PSP hardware but they will work on the PS3's PSP Remaster emulator (which was used for Monster Hunter Portable 3rd HD Ver.) and on unofficial emulators like PPSSPP.

Please add an additional optional patch for these HD iOS assets for emulators. Thanks in advance.

**Comment by IncognitoMan** [comment]
> The iOS version of Monster Hunter Portable 2nd G/Freedom Unite apparently has higher-resolution assets. Replacing the game with these assets would not work on real PSP hardware but they will work on the PS3's PSP Remaster emulator (which was used for Monster Hunter Portable 3rd HD Ver.) and on unofficial emulators like PPSSPP.
> 
> Please add an additional optional patch for these HD iOS assets for emulators. Thanks in advance.

The only real solution to this is to use PPSSPP's texture replacer.

P3rd HD is built around the fact that it knows how to address the additional memory of the PS3's PSP emulator and P2G only knows about the 24mb it can address. Without changing various aspects of the game to account for the new memory and changing addresses and allocations made for the current files...  P2G assets will remain the same other than *maybe* some tweaks if memory allows.

The iOS version assets also have some compression/artifacts and need touch ups to fix them...

The other reason I probably won't do this is because I don't want to worry about another platform or specialized build of the patch... especially when PPSSPP's texture replacer has none of the limitations that P2G imposes (like for example a limit of 256 colors or 1bit alphas).
