### ISSUE TITLE
Things to be addressed for 1.3.1

### ISSUE THREAD

**Issue by IncognitoMan** [FUComplete/Patch#88]
This will be updated as issues are found or features are added...

- [x] #87 
  - [x] arcade_str 0 392
  - [x] str_tbl 0  1282
- [x] Implement multiple savedata icons for P2G and FU savedata. Allows JP saves to have P2G icon and NA/EU saves to have FU icon.
- [x] Make lao/shen early kill an config toggle.
- [x] Update file sizes for files that get skipped when using file replacer

**Comment by Thaitea666** [comment]
Can u make the full acces chest to be a config toggle too?

**Comment by IncognitoMan** [comment]
> Can u make the full chest acces to be a config toggle too? Like in the 1.2.1 the feature is optional with QoL cheat

Is there any particular reason to make it a config toggle? It's only accessible to offline guildhall as of 1.3.0a...

**Comment by UnknownZeroXX** [comment]
Can u make CQ to folder like ms0:/FUC/CustomQuests folder. So we can manage/use CQ easily and simple.
To manage CQ without save data re-editing. Just download .mib file, copy to ms0:/FUC/CustomQuest folder and ready to play

And I'm android user, so i can't access to FUC TOOL but i can use ready config.bin files so can u make ready different config.bin files for all users because FUC TOOL and configurations really hard to use always need PC. Thank You for trying to make FU/2G better

**Comment by Thaitea666** [comment]
> 

No, it's just my personal preference and only this feature that i not really into it, i think it's better to be an optional feature, i'ts ok if ur not agree

**Comment by Thaitea666** [comment]
> > Can u make the full chest acces to be a config toggle too? Like in the 1.2.1 the feature is optional with QoL cheat
> 
> Is there any particular reason to make it a config toggle? It's only accessible to offline guildhall as of 1.3.0a...

No, it's just my personal preference and only this feature that i not really into it, i think it's better to be an optional feature, i'ts ok if ur not agree
