### ISSUE TITLE
[BUG] ktx2 files

### ISSUE THREAD

**Issue by floydGG** [FUComplete/Patch#90]
It seems the latest patch have problem to load some of the textures with ktx2 extension (?)
And also this banned thing when i tried to dump textures
![image](https://user-images.githubusercontent.com/53382214/230226815-c57e0616-a480-466e-a408-3cadcc111e84.png)

**Comment by IncognitoMan** [comment]
So a few things...

1. In regards to the "filenames may not be cross-platform" warning, This is when you use upper case letters or any of the following: `:<>|?*`.
2. although you say some of the textures with ktx2 extension... please make sure you are running the most recent nightly, this is because ktx2 support was added recently.
3. Various textures did get updated with 1.3.0 (splash screens, UI textures, icons, etc), so you will have to make sure the textures in the ini match the ***new*** hashes.

If there's still a problem after checking those please send me a copy of the ini, a ktx2 texture that isn't getting loaded and what version of ppsspp you are running.

**Comment by floydGG** [comment]
Thanks for your response, the hashes changed for those u mentioned. I have to use empty .ini files to get those textures.
I am using ppsspp-v1.14.4-1150-gd65afcc7f, all good now.
